using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.SqlServer.Dac;
using Microsoft.SqlServer.Dac.Model;
using Sqloom.Core.Artifacts;
using Xunit;

namespace Sqloom.Host.Tests;

/// <summary>
/// Exercises DACPAC-backed SQL Server schema extraction.
/// </summary>
public sealed class SqlServerDacpacSchemaExtractorTests
{
    [Fact]
    public async Task UnpacksModelSqlIntoReplayArtifactDirectory()
    {
        var artifactDirectory = CreateTempDir();
        var expectedSchemaPath = ArtifactLayout.GetSqlServerSchemaPath(artifactDirectory);
        var expectedExtractDirectory = ArtifactLayout.GetSqlServerDacpacExtractDir(artifactDirectory);
        Directory.CreateDirectory(expectedExtractDirectory);
        var staleFilePath = Path.Combine(expectedExtractDirectory, "stale.txt");
        await File.WriteAllTextAsync(staleFilePath, "stale");
        var dacpacPath = CreateDacpacFixture(artifactDirectory);
        SqlServerDacpacSchemaExtractor extractor = new();

        var schemaPath = await extractor
            .ExtractAsync(
                dacpacPath,
                artifactDirectory)
            ;

        Assert.Equal(expectedSchemaPath, schemaPath, StringComparer.OrdinalIgnoreCase);
        Assert.True(File.Exists(schemaPath), $"Expected generated schema at '{schemaPath}'.");
        Assert.True(Directory.Exists(expectedExtractDirectory), $"Expected DACPAC extract directory at '{expectedExtractDirectory}'.");
        Assert.False(File.Exists(staleFilePath), $"Expected stale DACPAC extract file '{staleFilePath}' to be removed.");

        var modelSqlPath = Path.Combine(expectedExtractDirectory, "model.sql");
        Assert.True(File.Exists(modelSqlPath), $"Expected extracted DACPAC model SQL at '{modelSqlPath}'.");

        var schemaSql = await File.ReadAllTextAsync(schemaPath);
        Assert.Contains("dbo", schemaSql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Widget", schemaSql, StringComparison.OrdinalIgnoreCase);

        var modelSql = await File.ReadAllTextAsync(modelSqlPath);
        Assert.Equal(schemaSql, modelSql);
    }

    [Fact]
    public async Task ThrowsWhenDacpacIsMissing()
    {
        var artifactDirectory = CreateTempDir();
        SqlServerDacpacSchemaExtractor extractor = new();

        var exception = await Assert.ThrowsAsync<ArgumentException>(
            () => extractor.ExtractAsync(
                Path.Combine(artifactDirectory, "missing.dacpac"),
                artifactDirectory));

        Assert.Contains("SQL Server DACPAC", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    private static string CreateTempDir()
    {
        var directory = Path.Combine(
            Path.GetTempPath(),
            "sqloom-dacpac-schema-tests",
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        return directory;
    }

    private static string CreateDacpacFixture(string directory)
    {
        var dacpacPath = Path.Combine(directory, "sqloom-test-schema.dacpac");
        using TSqlModel model = new(
            SqlServerVersion.Sql170,
            new TSqlModelOptions());
        model.AddObjects(
            """
            CREATE TABLE [dbo].[Widget]
            (
                [Id] INT NOT NULL,
                [Name] NVARCHAR(100) NULL,
                CONSTRAINT [PK_Widget] PRIMARY KEY CLUSTERED ([Id] ASC)
            );
            """);

        DacPackageExtensions.BuildPackage(
            dacpacPath,
            model,
            new PackageMetadata
            {
                Name = "SqloomTestSchema",
                Version = "1.0.0.0",
                Description = "Generated by Sqloom unit tests.",
            });
        return dacpacPath;
    }
}
