using System;
using System.Text;

namespace Sqloom.Host;

/// <summary>
/// Renders the deterministic command reference from the Sqloom command catalog.
/// </summary>
public static class CommandReferenceMarkdown
{
    /// <summary>
    /// Gets the repository-relative path of the generated command reference.
    /// </summary>
    public const string RelativePath = ".agents/skills/sqloom/references/commands.md";

    /// <summary>
    /// Renders the complete command reference as Markdown.
    /// </summary>
    public static string Render()
    {
        StringBuilder builder = new();
        builder.AppendLine("# Sqloom Command Reference");
        builder.AppendLine();
        builder.AppendLine("Generated from the command catalog in `Sqloom.Host`. Do not edit this file directly.");
        builder.AppendLine();
        builder.AppendLine("## Tool options");
        builder.AppendLine();
        AppendOptions(builder, CommandCatalog.ToolOptions);
        builder.AppendLine("## Commands");
        builder.AppendLine();

        foreach (var command in CommandCatalog.Commands)
        {
            builder.Append("### `").Append(command.Verb).AppendLine("`");
            builder.AppendLine();
            builder.AppendLine(command.Description);
            builder.AppendLine();
            builder.AppendLine("```text");
            builder.Append("sqloom ").AppendLine(command.Usage);
            builder.AppendLine("```");
            builder.AppendLine();

            if (command.TargetKind != CommandTargetKind.None)
            {
                var requirement = command.TargetKind == CommandTargetKind.Required ? "Required" : "Optional";
                builder.Append("**Target:** ").Append(requirement).AppendLine(" `<path>` to a harness project, assembly, solution, solution filter, or directory.");
                builder.AppendLine();
            }

            if (command.SupportsDebug || command.SupportsHarnessOptions)
            {
                builder.AppendLine("#### Startup options");
                builder.AppendLine();
                foreach (var option in CommandCatalog.StartupOptions)
                {
                    if (option.Name == "--debug" && !command.SupportsDebug
                        || option.Name != "--debug" && !command.SupportsHarnessOptions)
                    {
                        continue;
                    }

                    AppendOption(builder, option);
                }

                builder.AppendLine();
            }

            if (command.Options.Count > 0)
            {
                builder.AppendLine("#### Command options");
                builder.AppendLine();
                AppendOptions(builder, command.Options);
            }
        }

        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void AppendOptions(StringBuilder builder, System.Collections.Generic.IReadOnlyList<CommandOptionSpec> options)
    {
        foreach (var option in options)
        {
            AppendOption(builder, option);
        }

        builder.AppendLine();
    }

    private static void AppendOption(StringBuilder builder, CommandOptionSpec option)
    {
        builder.Append("- `").Append(option.Syntax).Append("` - ").Append(option.Description);
        if (option.IsRequired)
        {
            builder.Append(" Required.");
        }

        if (option.DefaultValue is not null)
        {
            builder.Append(" Default: `").Append(option.DefaultValue).Append("`.");
        }

        builder.AppendLine();
    }
}
